# -*- coding: utf-8 -*-
"""prima3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1knAknwNVX9KVk9QJhzjmxLKrHfhHMh1R

# Part 3

## 0. Which table contains data with issues? What are all the issues you can identify in this table?

We start by importing the libraries we are going to use.
"""

import pandas as pd
import numpy as np

"""First, we load the tables and conduct preliminary analysis to identify any issues. We inspect each table separately. In each table we iterate the same process:


* Load the table
* General info
* Preview first rows of the table
* Display descriptive statistics
* Check duplicated rows
* Check null values
* Trim string values and lowercase

### **POLICIES TABLE ANALYSIS**
"""

policies = pd.read_csv('policies.csv', parse_dates=[2]) # parse 'date' column
policies.info()
policies.head()

policies.describe()

"""We look for duplicates."""

policies.duplicated().sum()

"""We look for null values."""

policies.isnull().sum()

"""### **PRICES TABLE ANALYSIS**"""

prices = pd.read_csv('prices.csv')
prices.info()
prices.head()

prices.describe()

prices.duplicated().sum()

"""As I have found that there are 88 rows duplicated, I'm going to take a look at them keeping all duplicated rows ordered by `id`."""

prices[prices.duplicated(keep=False)].sort_values('id')

"""I'm going to drop duplicated rows, keeping the last occurance, and double check if we still have duplicates in the table."""

prices.drop_duplicates(keep='last', inplace=True)
prices.duplicated().sum()

len(prices) #It should be 30088 - 88 = 30000

"""I am going to look for null values."""

prices.isnull().sum()

"""Let's dive into the `premium`column and filter by null values to inspect if there is any reason or pattern for those null values."""

premium_nan = prices[prices['premium'].isnull()]
premium_nan.head()

"""I assume that `NaN` values in the column `premium` should not be part of the analysis, so I am going to drop those rows from the table and raise the problem to the sales team sending them `premium_nan` info."""

prices.dropna(subset=['premium'], inplace=True)

prices.head()

"""We are going to inspect `product_type` column looking for trim spaces, and then we will change the data type to `category`."""

prices['product_type'].str.strip()
prices['product_type'].str.strip().value_counts()

prices[prices['product_type'] == 'none']

"""The information we received says that the colum `product_type`can only be: `breakdown`, `full`or `legal`. For that reason, we are going to drop rows with `none`as `product type`."""

prices = prices[prices['product_type'] != 'none']
prices.product_type.value_counts()

"""### **QUOTES TABLE ANALYSIS**"""

quotes = pd.read_csv('quotes.csv', parse_dates=[1])
quotes.info()
quotes.head()

quotes.describe()

quotes.duplicated().sum()

quotes.isnull().sum()

quotes['email'].str.strip().str.lower()
quotes['operation_type'].str.strip().str.lower()
quotes.head()

quotes.operation_type.value_counts()

"""We assume `operation_type` won't easily change in the future, so we are going swap its data type to `category`."""

quotes['operation_type'] = quotes['operation_type'].astype('category')
quotes.info()

"""### **VEHICLES TABLE ANALYSIS**"""

vehicles = pd.read_csv('vehicles.csv')
vehicles.info()
vehicles.head()

vehicles.describe()

vehicles.duplicated().sum()

vehicles['vehicle_type'].value_counts()

vehicles['vehicle_type'].str.strip().str.lower()
vehicles.head()

vehicles['city'].value_counts()

"""## 1. What are the most quoted vehicle_id and vehicle_type in H2 2021?"""

quotes_vehicles = pd.merge(
    quotes,
    vehicles,
    left_on = 'vehicle_id',
    right_on = 'id',
    suffixes = ('_quotes', '_vehicles'),
    how='inner')

quotes_vehicles_policies = pd.merge(
    quotes_vehicles,
    prices,
    left_on = 'id_quotes',
    right_on = 'id',
    suffixes = (('_quotes', '_vehicles'), '_prices'),
    how='inner')

quotes_vehicles_policies.head()

quotes_vehicles_policies.info()

quotes_vehicles_policies.duplicated().sum()

h2_2021 = quotes_vehicles_policies[(quotes_vehicles_policies['date'] < '2022-01-01') & (quotes_vehicles_policies['date'] > '2021-06-30')]
h2_2021.sort_values('premium', ascending=False)

h2_2021.isnull().sum()

h2_2021_max_quote = h2_2021.premium.max()
h2_2021_max_quote

h2_2021_most_quoted = h2_2021[h2_2021['premium'] == h2_2021_max_quote]
h2_2021_most_quoted[['vehicle_id', 'premium']]

"""Now, I am going to calculate the most quoted vehicle_type in H2 2021."""

h2_2021[['vehicle_type', 'premium']].groupby('vehicle_type').agg(
    {'premium': ['sum', 'mean']}
)

"""## 2. What is the month with the highest increase in unique quoting customers with respect to the previous month?

I will measure the increase in unique customers in absolute and percentage terms.

First, I am going to aggregate all the dates under the same month into a single bin.
"""

quotes_vehicles_policies['year_month'] = quotes_vehicles_policies['date'].dt.to_period('M')
df_monthly_customers = quotes_vehicles_policies.groupby('year_month')['id_quotes'].nunique().reset_index(name='count_customers')
df_monthly_customers

"""Next, I'm going to compare each month's data with that of the previous month and calculate the difference between them in absolute and percentage terms.



"""

df_monthly_customers['prev_count'] = df_monthly_customers['count_customers'].shift(1)
df_monthly_customers['prev_count'] = pd.to_numeric(df_monthly_customers['prev_count'], errors='coerce', downcast="integer")
df_monthly_customers['diff'] = df_monthly_customers['count_customers'] - df_monthly_customers['prev_count']
df_monthly_customers['pct_change'] = df_monthly_customers['count_customers'].pct_change()
df_monthly_customers

"""I am going to calculate the maximum figures for `diff` and `pct_change` columns.




"""

max_diff = df_monthly_customers[['year_month', 'diff']][df_monthly_customers['diff'] == df_monthly_customers['diff'].max()]
max_diff

max_pct_change = df_monthly_customers[['year_month', 'pct_change']][df_monthly_customers['pct_change'] == df_monthly_customers['pct_change'].max()]
max_pct_change

"""Let's see the results above graphically using Matplotlib."""

from matplotlib import pyplot as plt

df_monthly_customers['months'] = df_monthly_customers['year_month'].astype(str)

x = np.arange(len(df_monthly_customers))
width = 0.35

plt.figure(figsize=(12,6))

# Current month
plt.bar(x - width/2, df_monthly_customers['count_customers'], width, color='#8C38D7', label='Current Month')

# Previous month
plt.bar(x + width/2, df_monthly_customers['prev_count'], width, color='#5B2488', label='Previous Month')

plt.xlabel('Date')
plt.ylabel('# Customers')
plt.title('Comparison of unique customer per month')
plt.xticks(x, df_monthly_customers['months'], rotation=45)
plt.legend()
plt.tight_layout()
plt.show()

colors = df_monthly_customers['pct_change'].apply(
    lambda x: '#8C38D7' if x > 0 else 'orange')

plt.figure(figsize=(10,5))
plt.bar(df_monthly_customers['months'], df_monthly_customers['diff'], color = colors)
plt.axhline(0, color='black', linewidth=1)

plt.xlabel('Dates')
plt.ylabel('Percentage')
plt.title('Difference in customers between current and previous month')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

plt.figure(figsize=(10,5))
plt.bar(df_monthly_customers['months'], df_monthly_customers['pct_change'], color=colors)
plt.axhline(0, color='black', linewidth=1)

plt.xlabel('Dates')
plt.ylabel('Percentage')
plt.title('Monthly Percentage Change')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

"""## 3. Which product_type has the highest conversion percentage (purchases / quotes)?"""

quotes_prices = pd.merge(
    quotes,
    prices,
    left_on = 'id',
    right_on = 'quote_id',
    suffixes = ('_quotes', '_prices')
    )

quotes_prices_policies = pd.merge(
    quotes_prices,
    policies,
    left_on = 'id_prices',
    right_on = 'price_id',
    suffixes = ('_quotes', '_policies'),
    how = 'left'
    )
quotes_prices_policies

df = quotes_prices_policies[['id_quotes', 'id_prices', 'product_type', 'id']]
df.rename(
    columns = {
        'id_prices' : 'id_quote_product',
        'id' : 'id_purchase'
    },
    inplace = True
)
df

"""Let's count the number of quotes created and the number of policies sold."""

df_by_product_type = df.groupby('product_type').agg(
    {'id_quotes': 'nunique',
     'id_purchase': 'count'}
)
df_by_product_type

df_by_product_type['conv_rate'] = df_by_product_type['id_purchase']/df_by_product_type['id_quotes']
df_by_product_type

max_conv_rate = df_by_product_type[df_by_product_type['conv_rate'] == df_by_product_type['conv_rate'].max()]
max_conv_rate

